### ISSUE TITLE
Create data dump for Pelagios

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-data-rdf#1]
Add all files to a single (or 10ish) RDF files add link to compiled files to VOID file.

**Comment by wsalesky** [comment]
@davidamichelson This is ready for testing. 
Link to void file: 
https://raw.githubusercontent.com/srophe/srophe-data-rdf/master/rdf/srophe/places.void.rdf

Link to dump file: 
https://raw.githubusercontent.com/srophe/srophe-data-rdf/master/rdf/srophe/places-pelagios.rdf

**Comment by davidamichelson** [comment]
Thanks!

**Comment by wsalesky** [comment]
stale issue.
